# Generated by Django 3.2.3 on 2021-06-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugmodel',
            name='status',
            field=models.CharField(choices=[('NO', 'New'), ('IP', 'In Progress'), ('DO', 'Done'), ('IN', 'Invalid')], default='NO', max_length=2),
        ),
    ]
